channels:
- conda-forge
dependencies:
- coverage
- google-api-python-client =2.190.0
- google-auth =2.48.0
- google-auth-oauthlib =1.2.2
- numpy =2.4.0
- pandas =2.3.3
- python
- scikit-learn =1.8.0
- sqlalchemy =2.0.47
- tqdm =4.67.3
- hatchling
- hatch-vcs
